server:
  port: 8081
  address: 0.0.0.0

spring:
  application:
    name: AUTH-SERVICE
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:mysql://194.24.161.189:3306/jobs_db
    username: leadlocator
    password: Lead@1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://194.24.161.189:8761/eureka

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG