server:
  port: 8085
  address: 0.0.0.0

spring:
  application:
    name: ONBOARD-SERVICE

  datasource:
    url: jdbc:mysql://194.24.161.189:3306/jobs_db
    username: leadlocator
    password: Lead@1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
        max-request-size: 30MB
        max-file-size: 30MB

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-registry: true
    service-url:
      defaultZone: http://194.24.161.189:8761/eureka