server:
  port: 8761
  address: 0.0.0.0


eureka:
  instance:
    hostname: 194.24.161.189
    prefer-ip-address: true
  client:
    register-with-eureka: false
    service-registry: false
    service-url:
      defaultZone: http://194.24.161.189:8761/eureka