server:
  port: 8080
  # API Gateway runs on this port
  address: 0.0.0.0

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: AUTH-SERVICE
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
            - id: LEADMANAGEMENT
              uri: lb://LEADMANAGEMENT
              predicates:
                - Path=/api/leads/**
            - id: ONBOARD-SERVICE
              uri: lb://ONBOARD-SERVICE
              predicates:
                - Path=/onboard/**
            - id: CRAWLER-SERVICE
              uri: lb://CRAWLER-SERVICE
              predicates:
                - Path=/jobs/**
            - id: PROFILE-SERVICE
              uri: lb://PROFILE-SERVICE
              predicates:
                - Path=/profile/**

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns:
                  - "https://leadslocator.orangebits.click/"   # your frontend
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
                maxAge: 3600

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
 