server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: AUTH-SERVICE
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=0

            - id: LEADMANAGEMENT
              uri: lb://LEADMANAGEMENT
              predicates:
                - Path=/api/leads/**
              filters:
                - StripPrefix=0

            - id: ONBOARD-SERVICE
              uri: lb://ONBOARD-SERVICE
              predicates:
                - Path=/onboard/**
              filters:
                - StripPrefix=0

            - id: CRAWLER-SERVICE
              uri: lb://CRAWLER-SERVICE1
              predicates:
                - Path=/jobs/**
              filters:
                - StripPrefix=0

            - id: COMPANY-SERVICE
              uri: lb://COMPANY-SERVICE
              predicates:
                - Path=/api/companies/**
              filters:
                - StripPrefix=0

            - id: PROFILE-SERVICE
              uri: lb://PROFILE-SERVICE
              predicates:
                - Path=/profile/**
              filters:
                - StripPrefix=0

          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOriginPatterns:
                  - "https://leadslocator.orangebits.click"
                  - "http://localhost:*"
                  - "http://127.0.0.1:*"
                  - "http://194.24.161.189:*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                  - PATCH
                allowedHeaders: 
                  - "*"
                exposedHeaders:
                  - "Authorization"
                  - "Content-Type"
                  - "X-Requested-With"
                  - "Accept"
                  - "Origin"
                  - "Access-Control-Request-Method"
                  - "Access-Control-Request-Headers"
                allowCredentials: true
                maxAge: 3600

    loadbalancer:
      health-check:
        interval: 10s
      retry:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://194.24.161.189:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: 194.24.161.189

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      access: read-only

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.netflix.discovery: INFO
    org.springframework.web.cors: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
