server:
  port: 8080
  # API Gateway runs on this port
  address: 0.0.0.0

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
            - id: client-service
              uri: lb://CLIENT-SERVICE
              predicates:
                - Path=/client/**
            - id: onboard-service
              uri: lb://ONBOARD-SERVICE
              predicates:
                - Path=/onboard/**
            - id: crawler-service
              uri: lb://CRAWLER-SERVICE
              predicates:
                - Path=/crawler/**

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns:
                  - "https://leadslocator.orangebits.click/"   # your frontend
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
                maxAge: 3600

eureka:
  client:
    service-url:
      defaultZone: http://194.24.161.189:8761/eureka/
 