server:
  port: 8087
  address: 0.0.0.0

spring:
  application:
    name: LEADMANAGEMENT

  datasource:
    url: jdbc:mysql://194.24.161.189:3306/jobs_db
    username: leadlocator
    password: Lead@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-registry: true
    service-url:
      defaultZone: http://194.24.161.189:8761/eureka

